In [3]:
#Importing numpy library into notebook
import numpy as np

In [4]:
#Creating array using inbuilt method
arr = np.array([10,20,30,40])

In [5]:
print(arr)

[10 20 30 40]


In [6]:
#Printing array
arr

array([10, 20, 30, 40])

In [7]:
type(arr)

numpy.ndarray

In [8]:
#Creating multi-dimensional array
arr2 = np.array([[10,20,20,30], [30,20,40,50]])
arr2

array([[10, 20, 20, 30],
       [30, 20, 40, 50]])

In [9]:
#Creating a array intialized to 0
#1st parameter - no of rows
#2nd Parameter - no of columns
arr3 = np.zeros([3,4])

In [10]:
arr3

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [11]:
#Initializing array with a specific number
#1st, 2nd parameters same
#3rd parameter- number to be filled with
arr4 = np.full([5,4], 20)
arr4

array([[20, 20, 20, 20],
       [20, 20, 20, 20],
       [20, 20, 20, 20],
       [20, 20, 20, 20],
       [20, 20, 20, 20]])

In [13]:
#arange method - used to print numbers in a particular range
arr5 = np.arange(10,60,7)
arr5

array([10, 17, 24, 31, 38, 45, 52, 59])

In [14]:
#1st, 2nd parameter - Range of numbers
#3rd parameter - Difference we want between two numbers
arr6 = np.arange(10,150,10)
arr6

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110, 120, 130,
       140])

In [15]:
#random method - used to print random numbers in a range
arr7 = np.random.randint(1,100,6)
arr7

array([33, 24, 56, 82, 94,  5], dtype=int32)

In [16]:
#1st, 2nd parameter - range
#3rd parameter - Quantity of random numbers we want from that range
arr8 = np.random.randint(200,500,14)
arr8

array([388, 458, 299, 347, 325, 313, 488, 275, 333, 215, 398, 486, 274,
       254], dtype=int32)

In [20]:
#checking the shape of an array
arr4.shape

(4, 5)

In [19]:
#changing the shape of an array
arr4.shape = (4,5)
arr4.shape

(4, 5)

In [21]:
#Stacking of arrays

In [22]:
#vstack - vertical stack
n1 = np.array([10,20,30])
n2 = np.array([40,50,60])
np.vstack((n1,n2))

array([[10, 20, 30],
       [40, 50, 60]])

In [23]:
#hstack - horizontal stack
n3 = np.array([10,20,30])
n4 = np.array([40,50,60])
np.hstack((n3,n4))

array([10, 20, 30, 40, 50, 60])

In [24]:
#column_stack - stacking one array in one column
n5 = np.array([10,20,30])
n6 = np.array([40,50,60])
np.column_stack((n5,n6))

array([[10, 40],
       [20, 50],
       [30, 60]])

In [25]:
#hstack - horizontal stack
n3 = np.array([10,20,30])
n4 = np.array([40,50,60])
np.hstack((n4,n3))

array([40, 50, 60, 10, 20, 30])

In [27]:
#column_stack - stacking one array in one column
n5 = np.array([10,20,30])
n6 = np.array([40,50,60])
np.column_stack((n6,n5))

array([[40, 10],
       [50, 20],
       [60, 30]])

In [28]:
#Intersection and Difference of Arrays

In [32]:
#Intersect - common numbers
new = np.array([1,2,3,4,5,6,7,8,9])
old = np.array([5,6,7,8,9,0,11,13,14])
np.intersect1d(new,old)

array([5, 6, 7, 8, 9])

In [33]:
#Set Difference - Present in 1st array but not in 2nd
np.setdiff1d(new,old)

array([1, 2, 3, 4])

In [34]:
#Set Difference
np.setdiff1d(old,new)

array([ 0, 11, 13, 14])